# Чтобы установить тему оформления нужно ереименовать _config.txt в _config.yml  

theme: jekyll-theme-minimal
title: [ABC]
description: [Введение в семейство операционных систем]

#show_downloads: ["true" or "false" to indicate whether to provide a download URL]
#google_analytics: [Your Google Analytics tracking ID]
